### ISSUE TITLE
Проблема с модом

### ISSUE THREAD

**Issue by demidovskiy** [AantCoder/OnlineCity#40]
Добрый день, возможно это не совсем к Вам, но всё же, есть проблема при подключении мода: Expanded Prosthetics and Organ Engineering: [воркшопстим](https://steamcommunity.com/sharedfiles/filedetails/?id=725956940&searchtext=Expanded+Prosthetics+and+Organ+Engineering)
Настроил синхронизацию модов, есть около 15+ который установлены. После установки мода Expanded Prosthetics and Organ Engineering, при попытке подключения, в консоли сервера вознимает ошибка:

```
02.07.2020 20:24:46 |     0 |   1 | Server Load...
02.07.2020 20:24:46 |    19 |   1 | Server Version data: Version 0.03.44a from 2020.06.11 Current version: Version 0.03.44a from 2020.06.11
02.07.2020 20:24:46 |     6 |   1 | Server Load done. Users 5: system, discord, demidovskiy, CryBit, Vatrushka
02.07.2020 20:24:46 |     7 |   1 | Server Saving
02.07.2020 20:24:46 |    12 |   1 | Server Saved
02.07.2020 20:24:46 |     5 |   1 | Calc hash E:\Bin\World\Mods
02.07.2020 20:24:47 |   382 |   1 | Calc hash 
02.07.2020 20:24:47 |    61 |   1 | Server starting on port: 19019
02.07.2020 20:24:53 |     0 |   7 | New connect
02.07.2020 20:24:53 |     7 |   7 | Server ReceiveBytes1
02.07.2020 20:24:53 |    30 |   7 | Server SendMessage1
02.07.2020 20:24:54 |   113 |   7 | Server       LoginByPassword
02.07.2020 20:24:58 |     0 |   8 | New connect
02.07.2020 20:24:58 |     5 |   8 | Server ReceiveBytes1
02.07.2020 20:24:58 |     5 |   8 | Server SendMessage1
02.07.2020 20:24:58 |   102 |   8 | Server       LoginByPassword
02.07.2020 20:24:58 |   111 |   8 | Server demidovskiy ServerInformation
02.07.2020 20:24:58 |   113 |   8 | Server demidovskiy GetApprovedFolders
02.07.2020 20:24:58 |   318 |   8 | Server demidovskiy CheckFiles
02.07.2020 20:24:58 |    17 |   8 | Exception GetPackage: System.NullReferenceException: Object reference not set to an instance of an object.
   at ServerOnlineCity.Services.CheckFiles.checkFiles(ModelModsFiles packet, ServiceContext context)
   at ServerOnlineCity.Services.CheckFiles.GenerateModelContainer(ModelContainer request, ServiceContext context)
   at ServerOnlineCity.Service.GetPackage(ModelContainer inputPackage)
   at ServerOnlineCity.SessionServer.Do(ConnectClient client)
02.07.2020 20:24:58 |   107 |   8 | Server demidovskiy CheckFiles
02.07.2020 20:24:58 |     5 |   8 | Exception GetPackage: System.NullReferenceException: Object reference not set to an instance of an object.
   at ServerOnlineCity.Services.CheckFiles.checkFiles(ModelModsFiles packet, ServiceContext context)
   at ServerOnlineCity.Services.CheckFiles.GenerateModelContainer(ModelContainer request, ServiceContext context)
   at ServerOnlineCity.Service.GetPackage(ModelContainer inputPackage)
   at ServerOnlineCity.SessionServer.Do(ConnectClient client)

```

В чём может быть проблема?

**Comment by Roman8x** [comment]
Не поддерживаем синхронизацию Steam Пакетов,
