### ISSUE TITLE
Падение на Windows Server 2019

### ISSUE THREAD

**Issue by amatol** [AantCoder/OnlineCity#46]
Версия сервера: 0.03.46a
Любая попытка запуска приводит к:

```
10.01.2021 14:46:54 |     0 |   1 | Server Load...
Unhandled exception. System.ArgumentException: Object of type 'System.Int64' cannot be converted to type 'System.Int32'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at System.Reflection.FieldInfo.SetValue(Object obj, Object value)
   at System.Runtime.Serialization.FormatterServices.PopulateObjectMembers(Object obj, MemberInfo[] members, Object[] data)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObjectEnd(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at ServerOnlineCity.Repository.Load()
   at ServerOnlineCity.ServerManager.Start(String path)
   at ServerOnlineCity.Program.Main(String[] args)
```

**Comment by amatol** [comment]
С чистым сейвом запустилось без проблем. Видимо проблема после обновления сервера с текущим сейфом на новую версию.

**Comment by AantCoder** [comment]
Вы с ветки dev последнюю версию брали?

**Comment by amatol** [comment]
Я забрал сборку из группы ВК.

**Comment by AantCoder** [comment]
Похоже переход на 0.03.46a не совместим с данными из старой версии
